### ISSUE TITLE
xAxes range is not working as expected

### ISSUE THREAD

**Issue by PraveenKumarIlla** [MichaelVoelkel/ChartJs2QML#8]
Hi Team,

I have experienced an issue with chart js. I have defined xAxes as below

"scales": {
                    "xAxes": [{
                                        ticks: {
                                                          maxTicksLimit: 6,
                                                          min: 1623177453,
                                                          max: 1623230798,
                                                          stepSize: 10669, 
                                                }
                                     }]
              }
I am expecting the ticks to be 6 (i.e., starting from the origin) and the tics values to be 1623177453, 1623188122, 1623198791, 1623209460, 1623220129 and 1623230798.

But the output is giving only 4 ticks (1623177453, 1623198791, 1623220129 and 1623230798).

Please let me know if am doing anything wrong. Please suggest

![trends_pic](https://user-images.githubusercontent.com/85723533/123387917-e902be00-d5b5-11eb-83b1-eb811a418eae.PNG)

**Comment by PraveenKumarIlla** [comment]
Hi Team,
Can any one please support me on this

**Comment by MichaelVoelkel** [comment]
Hi! We only pass this to ChartJS in the backend, this repo is only a wrapper for it. Or is it working fine with the ChartJS part? It seems that ChartJS sees it merely as recommendation in your case...
